version: '3.8'
services:
  Sep4-ModelTraining-Service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5010:5000"
    image: sep4-python-env
    container_name: Model-Training-Container
    volumes:
         - ../TrainModel/TrainedModels:/app/TrainModel/TrainedModels
    working_dir: /app/TrainModel
    command:  python ModelTrainingAPI.py
    stdin_open: true
    tty: true
  Sep4-DataProcessing-Service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    image: sep4-python-env
    container_name: Data-Processing-Container
    working_dir: /app/DataProcessing
    command:  python DataProcessing.py
    stdin_open: true
    tty: true
  Sep4-API-Service:
    build:
      context: ../APII
      dockerfile: Dockerfile
    image: sep4-dotnet-env
    container_name: API-container
    ports:
      - "5020:8080"  # 
    depends_on:
      - Sep4-DataProcessing-Service
  Sep4-ML-Service:
    build:
      context: ../MLService
      dockerfile: Dockerfile
    image: sep4-dotnet-env
    container_name: ML_Service-container
    ports:
      - "5030:8080"  # Maps port 5030 on the host to port 8080 in the container
    depends_on:
      - Sep4-ModelTraining-Service
    environment:
      - ASPNETCORE_URLS=http://+:8080  # Configure the app to listen on port 8080

