services:
  sep4-python-env:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    image: sep4-python-env
    container_name: ml-container
    volumes:
         - ../TrainModel/TrainedModels:/app/TrainModel/TrainedModels
    working_dir: /app/TrainModel
    command:  python ModelTrainingAPI.py
    stdin_open: true
    tty: true